name: AdvancedInvisibleItemframes
main: me.dasshark.advancedInvisibleItemframes.Main
version: 1.35-dev
api-version: 1.19
description: A plugin that adds invisible itemframes. Also modified to support glow item frames.
authors: [DasShark, Fjc]
commands:
  advancedinvisibleitemframes:
    aliases: aiif
    permission: advancedinvisibleitemframes.command
